//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace View.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of View.DtoClasses.Post from the entity model.</summary>
	public static partial class PostPersistence
	{
		#region Statics
		private static readonly System.Linq.Expressions.Expression<Func<Let3arafo.Data.EntityClasses.PostEntity, View.DtoClasses.Post>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Let3arafo.Data.EntityClasses.PostEntity, View.DtoClasses.Post> _compiledProjector = CreateProjectionFunc().Compile();
		#endregion	
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static PostPersistence()
		{
		}
	
		/// <summary>Extension method which produces a projection to View.DtoClasses.Post which instances are projected from the 
		/// results of the specified baseQuery, which returns Let3arafo.Data.EntityClasses.PostEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve View.DtoClasses.Post instances</returns>
		public static IQueryable<View.DtoClasses.Post> ProjectToPost(this IQueryable<Let3arafo.Data.EntityClasses.PostEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		
		/// <summary>Extension method which produces a projection to View.DtoClasses.Post which instances are projected from the
		/// Let3arafo.Data.EntityClasses.PostEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Let3arafo.Data.EntityClasses.PostEntity instance created from the specified entity instance</returns>
		public static View.DtoClasses.Post ProjectToPost(this Let3arafo.Data.EntityClasses.PostEntity entity)
		{
			return _compiledProjector(entity);
		}

		
		private static System.Linq.Expressions.Expression<Func<Let3arafo.Data.EntityClasses.PostEntity, View.DtoClasses.Post>> CreateProjectionFunc()
		{
			return p__0 => new View.DtoClasses.Post()
			{
				CreatedByUserId = p__0.CreatedByUserId,
				Creator = new View.DtoClasses.PostTypes.User()
				{
					CompanyId = p__0.User.CompanyId,
					Id = p__0.User.Id,
					IsActive = p__0.User.IsActive,
					IsConfirmed = p__0.User.IsConfirmed,
					Password = p__0.User.Password,
					PersonId = p__0.User.PersonId,
					UserName = p__0.User.UserName,
				},
				DateCreated = p__0.DateCreated,
				Id = p__0.Id,
				IsActive = p__0.IsActive,
				LastModified = p__0.LastModified,
				LastModifiedByUserId = p__0.LastModifiedByUserId,
				Text = p__0.Text,
			};
		}
		
		
	}
}


