//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace View.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Post'.</summary>
	[Serializable]
	[DataContract]
	public partial class Post
	{
		/// <summary>Gets or sets the CreatedByUserId field. Derived from Entity Model Field 'Post.CreatedByUserId (FK)'</summary>
		[DataMember]
		public System.Int32 CreatedByUserId { get; set; }
		/// <summary>Gets or sets the Creator field. </summary>
		[DataMember]
		public PostTypes.User Creator { get; set; }
		/// <summary>Gets or sets the DateCreated field. Derived from Entity Model Field 'Post.DateCreated'</summary>
		[DataMember]
		public System.DateTime DateCreated { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Post.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Post.IsActive'</summary>
		[DataMember]
		public System.Boolean IsActive { get; set; }
		/// <summary>Gets or sets the LastModified field. Derived from Entity Model Field 'Post.LastModified'</summary>
		[DataMember]
		public System.DateTime LastModified { get; set; }
		/// <summary>Gets or sets the LastModifiedByUserId field. Derived from Entity Model Field 'Post.LastModifiedByUserId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> LastModifiedByUserId { get; set; }
		/// <summary>Gets or sets the Text field. Derived from Entity Model Field 'Post.Text'</summary>
		[DataMember]
		public System.String Text { get; set; }
	}

	namespace PostTypes
	{
		/// <summary> DTO class which is derived from the entity 'User (User)'.</summary>
		[Serializable]
		[DataContract]
		public partial class User
		{
			/// <summary>Gets or sets the CompanyId field. Derived from Entity Model Field 'User.CompanyId (FK)'</summary>
			[DataMember]
			public Nullable<System.Int32> CompanyId { get; set; }
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'User.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'User.IsActive'</summary>
			[DataMember]
			public System.Boolean IsActive { get; set; }
			/// <summary>Gets or sets the IsConfirmed field. Derived from Entity Model Field 'User.IsConfirmed'</summary>
			[DataMember]
			public System.Boolean IsConfirmed { get; set; }
			/// <summary>Gets or sets the Password field. Derived from Entity Model Field 'User.Password'</summary>
			[DataMember]
			public System.String Password { get; set; }
			/// <summary>Gets or sets the PersonId field. Derived from Entity Model Field 'User.PersonId (FK)'</summary>
			[DataMember]
			public Nullable<System.Int32> PersonId { get; set; }
			/// <summary>Gets or sets the UserName field. Derived from Entity Model Field 'User.UserName'</summary>
			[DataMember]
			public System.String UserName { get; set; }
		}
	}

}




